### ISSUE TITLE
Autoloading more articles doesn't work if font is large

### ISSUE THREAD

**Issue by fenuks** [nkanaev/yarr#100]
I'm using Firefox, and if font is large, yarr doesn't load more articles when I get to the end of the articles list with <kbd>j</kbd>. I have full HD monitor, and can reproduce this issue with clean installation like so:

1. Create new profile with `firefox -P`
2. Load yarr, verify that autoloading works
3. Open about:config
4. Change `font.size.variable.x-western` to something large, in my case `32` is enough to cause the problem
5. Reload yarr, press <kbd>j</kbd> until end of the list, and yarr shouldn't automatically load more articles

As a workaround, it's still possible to trigger fetching more articles with mouse scroll.

There is one other unrelated thing that would be nice to be changed, so I guess I will write about it.

It would be nice if on mobile I could long tap article on list, and choose to open it on the new tab. I think that change would also allow to open article in new tab with scroll wheel. On normal key press (or tap), yarr would behave as it does now, and open article within its interface.

**Comment by nkanaev** [comment]
font size issue was fixed in https://github.com/nkanaev/yarr/commit/2a5692d9a714c5c02e27f5acc76ee8f96fd05261. thanks for reporting.

> It would be nice if on mobile I could long tap article on list, and choose to open it on the new tab. I think that change would also allow to open article in new tab with scroll wheel. On normal key press (or tap), yarr would behave as it does now, and open article within its interface.

that's a feature, and a hidden one. i'm not accepting any features at the moment & prefer not to have any "surprise" functionality. sorry.

**Comment by fenuks** [comment]
> font size issue was fixed in https://github.com/nkanaev/yarr/commit/2a5692d9a714c5c02e27f5acc76ee8f96fd05261. thanks for reporting.

Thanks. :)

> that's a feature, and a hidden one. i'm not accepting any features at the moment & prefer not to have any "surprise" functionality. sorry.

Sure thing, I was aware that you generally don't add new features. I'd argue, though, for sake of discussion, that it's more an improvement than *hidden* feature, and in my experience many SPA work this way, normal click opens a thing within an app, but middle click opens it in new tab. From RSS world, feedly does that. On desktop it's not that important since one has shortcuts, but unfortunately on phone, I find reading articles rather tedious.
