### ISSUE TITLE
No feeds found at the given url.

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#109]
https://bwtorrents.tv/rss.php?cat=210&passkey=e9a3196921f7244d3b11ae4a41d2d8a9
https://bwtorrents.tv/rss.php?feed=dl&cat=211&passkey=e9a3196921f7244d3b11ae4a41d2d8a9

No feeds were detected at the specified url in YARR, yet they operate well in other feed readers.

**Comment by nkanaev** [comment]
it appears to be working for me.
are you able to access the links from the host where *yarr* is deployed?
