### ISSUE TITLE
Can I deploy yarr on GitHub pages?

### ISSUE THREAD

**Issue by Leoijeon** [nkanaev/yarr#111]
Thanks for your work on yarr, this helps me a lot in read rss. I often use this in my computer, but when I'm not in home, I still want to use it. It's very easy to deploy a site by GitHub pages. But I don't know whether we can deploy yarr on GitHub or not.  
Hoping your response.
Thanks!

**Comment by arsfeld** [comment]
Yarr is not a static page, it needs a server to be running to serve you content, so it won't work on Github Pages. Me and some other people are running it in [fly.io](https://fly.io) though, it's very easy to get started and the free plan is more than enough. You get a nice sub-domain with automatic https.

I even have Github automatically deploying for me (you got to setup some secrets for that though), take a look at my repo: https://github.com/nkanaev/yarr/compare/master...arsfeld:yarr:master

**Comment by Leoijeon** [comment]
Thanks for you response! I'll try you advice!
