### ISSUE TITLE
Hosting base question

### ISSUE THREAD

**Issue by faridalizade** [nkanaev/yarr#117]
Hello,

1. Is it possible install yarr on Shared Hostings? 

Why I am asking, because of SSH and commands. Some hostings are restricted this features.

2. If yes, how can I get documentation?

3. If no, can I build it on MacOS and then upload it as a website?

Thank you.

**Comment by nkanaev** [comment]
Hello,

my knowledge on shared hosting may be a bit outdated, but If you mean the traditional website hosters and/or LAMP stack providers, then the answer is no. You need a virtual/dedicated host to run the application.

Cheers
