### ISSUE TITLE
The infinite scrolling doesn't load more posts with "down arrow" key

### ISSUE THREAD

**Issue by grigio** [nkanaev/yarr#118]
The infinite scroll doesn't work pressing "down key", it only works with "mouse wheel" or "trackpad" scrolling

Just to explain better

![Screenshot from 2022-11-14 23-34-35](https://user-images.githubusercontent.com/8074/201783197-676c3bd0-b900-48ac-9093-347dc2123d46.png)

Press down

![Screenshot from 2022-11-14 23-35-22](https://user-images.githubusercontent.com/8074/201783242-e11e40cd-99e5-41e6-a5bf-a4e26324c7ec.png)

the selection goes on the top of the list but..

.. if you scroll with the trackpad it loads more posts

![Screenshot from 2022-11-14 23-36-00](https://user-images.githubusercontent.com/8074/201783712-f8e9da59-c0f7-4af5-8fc1-89323d2aea59.png)

**Comment by nkanaev** [comment]
Loading more articles relies on the scrolling behaviour of the 2nd column. It fetches more items once reaching the bottom of the list.

Arrows keys were never meant for navigation. But others are extensively using it (https://github.com/nkanaev/yarr/issues/110#issuecomment-1231913574 fo ex.) and are running into unforeseen issues too. Therefore these need to be fixed.

I'll see what I can do.

**Comment by nkanaev** [comment]
fixed in https://github.com/nkanaev/yarr/commit/58d6a46e36e9c827cd4ccc3f1a571d0e6fbf21aa.
