### ISSUE TITLE
For high resolution screens, the sentences are too long

### ISSUE THREAD

**Issue by whaler-ragweed** [nkanaev/yarr#120]
For high resolution screens (for example, iMac 4.5K display), the sentences are too long to read easily. I think it is good If there are some spaces beside the contents (like Feedbin or Feedly does).

yarr (long sentences)
<img width="2240" alt="Screenshot 2022-12-12 at 7 42 11 PM" src="https://user-images.githubusercontent.com/33184148/207038570-5331163e-1e58-4600-a5c5-1ea0739ff647.png">

Feedbin for reference (centered)
<img width="2240" alt="Screenshot 2022-12-12 at 7 51 19 PM" src="https://user-images.githubusercontent.com/33184148/207038635-cecd36cf-894e-45cc-95f2-d2aedd3a295c.png">

**Comment by telemachus** [comment]
@whaler-ragweed This is a pretty easy fix if you're comfortable editing a CSS file and building the app manually.

```diff
diff --git a/src/assets/stylesheets/app.css b/src/assets/stylesheets/app.css
index ab7aae2..35fe024 100644
--- a/src/assets/stylesheets/app.css
+++ b/src/assets/stylesheets/app.css
@@ -351,6 +351,7 @@ select.form-control:not([multiple]):not([size]) {
 .content {
   overflow-wrap: break-word;
   line-height: 1.5;
+  max-width: 65ch;
 }
 
 .content img, .content video {
```

Default build:

<img width="1440" alt="Screen Shot 2023-01-11 at 5 53 54 PM" src="https://user-images.githubusercontent.com/62958/211947442-47c2e13b-2e0a-4fa0-bf11-b2f7a37db64a.png">


After the CSS tweak:

<img width="1440" alt="Screen Shot 2023-01-11 at 5 52 37 PM" src="https://user-images.githubusercontent.com/62958/211947462-b74b0e10-2d43-4030-bf56-1a37f240c718.png">


I'll noodle around with this a bit more and then make a pull request though I'm not sure whether @nkanaev would be interested in such a change.

**Comment by nkanaev** [comment]
resolved in https://github.com/nkanaev/yarr/commit/bd6322e5331e0d7695a0f0632f6139b52713a117.
