### ISSUE TITLE
Search returns no results

### ISSUE THREAD

**Issue by BMorearty** [nkanaev/yarr#126]
When I search, I get zero results. No matter what I search for.

Example: 

![2023-02-01 10 40 08](https://user-images.githubusercontent.com/16927/216133668-de46a9bc-eb03-4764-ac0e-27470787a526.gif)

Yarr running on a MacBook Pro, Apple M1, Ventura 13.1. 

I've tried Firefox, Chrome, and Safari.

I don't see any errors in the browser dev console.

**Comment by nkanaev** [comment]
Refreshing feeds should fix it.

There is a bug in the latest release where newly added feeds are not searchable. Fixed in https://github.com/nkanaev/yarr/commit/012b58bbe4f8083267cb88fcca43ae13f8884ff8.
