### ISSUE TITLE
[Question] Adding share button for pocket

### ISSUE THREAD

**Issue by mzfr** [nkanaev/yarr#131]
I understand that you don't want to introduce any 3rd party dependencies to it. But I'd like to add a share button where I can directly add the content to my pocket account.

I am willing to write/update the code myself and update my own fork if you can provide some guidance on where I should start looking.

So can you please tell me:

1. Where I should look for taking the scraped/crawled content from the panes (I believe Vue handles the frontend part)?
2. Where a new API endpoint be added (to which content from Step 1 will be sent), so I can basically do a POST request on the Pocket API, of that content to add the new article.

**Comment by nkanaev** [comment]
1. the endpoint URL for crawling/scraping content is [here](https://github.com/nkanaev/yarr/blob/v2.3/src/server/routes.go#L56).
2. see the above link, it should serve as good starting point.

**Comment by tsujigiri** [comment]
I may be beating a dead horse, but why not use Pocket's browser extension, right-click, Save to Pocket, instead? Seems like a simpler solution than adding Pocket buttons to everything and having to maintain them? Feeling like the guy saying "I couldn't help overhearing your conversation... three months ago...". :sweat_smile:

**Comment by mzfr** [comment]
@tsujigiri Using Pocket's Browser extension does make sense if you are reading the article on the website itself. But since yarr already had a feature for "Read Here" I mostly use that and then using Pocket's browser extension didn't help, that is why I wanted to add the button. And I was able to do it here(https://github.com/mzfr/yarr)

**Comment by tsujigiri** [comment]
@mzfr I right-click on the external link at the top and save to Pocket using the context menu. It's only one click more.
