### ISSUE TITLE
RSS: `<guid isPermalink=“true”>` isn’t being taken as the URL

### ISSUE THREAD

**Issue by adaszko** [nkanaev/yarr#143]
Hi!

This particular feed: https://huggingface.co/blog/feed.xml is missing the `<link>` element but according to [specs](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt), it is enough to set `<guid isPermalink=“true”>` and specify URL there.  yarr doesn’t seem to be doing it as the article don’t “open” for me.  Instead, the browser just re-opens yarr in a new tab.

Context: https://github.com/huggingface/blog/issues/42#issuecomment-1554080984

**Comment by nkanaev** [comment]
thanks for the report! fixed in https://github.com/nkanaev/yarr/commit/bc18557820ed7c2d137b3ebadd7dfdf599d725cc

**Comment by adaszko** [comment]
Awesome, thanks as well!

**Comment by julien-c** [comment]
that's awesome!
