### ISSUE TITLE
Image proxy to enhance privacy

### ISSUE THREAD

**Issue by sevospl** [nkanaev/yarr#147]
When reading articles in public networks such as a hotspot, images are loaded directly. For the sake of enhacing privacy I would suggest to add support for image proxy, e.g. by leveraging an already existing solution [morty](https://github.com/asciimoo/morty). It's also written in Golang, so should supposedly be easy to embedd into yarr.

While you're not a fan of 3rd party dependencies, I personally believe that such a feature is very crucial in terms of privacy. Each time I read an article, a DNS request will be made which is already an indicator of what blogs / portals I go on.

**Comment by nkanaev** [comment]
yarr already ships with content sanitization.

If privacy is the main concern, please consider using a VPN or OS-level proxy.

Besides, the solution won't guard against directly opening the links, which will result in exposing you to the "dangers" of the internet anyways. Yarr is a privacy respecting tool, but not privacy enforcing one.
