### ISSUE TITLE
Spacing between an image and a paragraph are too close

### ISSUE THREAD

**Issue by whaler-ragweed** [nkanaev/yarr#149]
In some feeds, an image and a paragraph (which is the content, not a description of the image) are too close, and in other feeds they are well-situated. Don't know if it is a bug. Should we make the spacing consistent? 
<img width="1958" alt="1" src="https://github.com/nkanaev/yarr/assets/33184148/88b9f35e-a981-45c2-a717-9d933080048c">
<img width="1955" alt="2" src="https://github.com/nkanaev/yarr/assets/33184148/c3d68b77-b892-4d06-97e7-2655aba25569">
<img width="1959" alt="3" src="https://github.com/nkanaev/yarr/assets/33184148/de7c2844-96fe-495a-b3a7-62127d054e28">

**Comment by nkanaev** [comment]
partially resolved in https://github.com/nkanaev/yarr/commit/a96fc101f25d7c227866df4790f8932b189ab139.

some feeds (macrumors, as an example) provide content in non-semantic html (div abuse), which is hard to resolve without breaking image rendering in other feeds (inline images).
