### ISSUE TITLE
Add advanced filtering

### ISSUE THREAD

**Issue by Xant1k** [nkanaev/yarr#150]
Where the title or address can contain various filtering rules, including using regexp. Similar to how it's done in the https://siftrss.com/ service (look pic https://i.postimg.cc/dVZ9KYnq/chrome-FSAXIq-Xn-GN-2023-08-04-12-09-18.png) or in the [feedbro extension](https://chrome.google.com/webstore/detail/feedbro/mefgmmbdailogpfhfblcnnjfmnpnmdfa) (look pic https://nodetics.com/feedbro/shots/rule-dialog.png)

It would be great to filter out unnecessary entries in the feed. As an example, I often receive news headlined Nickelback - Fifty Gifty 2050 _FLAC+.CUE_ and Nickelback - Fifty Gifty 2050 _IMAGE+.CUE_ and Nickelback - Fifty Gifty 2050 _APE_
And with help of regexp in Opera Mail, I sort out the unnecessary and get only header with _APE_.

**Comment by nkanaev** [comment]
Please read https://github.com/nkanaev/yarr/issues/57.
