### ISSUE TITLE
Relative URLs in Atom feed don't work

### ISSUE THREAD

**Issue by adaszko** [nkanaev/yarr#153]
The feed in question: https://bjorn3.github.io/feed.xml

Since its URLs are relative (e.g. `<link href="/2023/07/29/progress-report-july-2023.html"...`), the articles are opened relative to yarr's instance URL, not feed's, resulting in 404s of course.  I'm not sure what the specs say but wouldn't it be more useful to glue the relative URLs to the feed's base URL?

Thanks!

**Comment by nkanaev** [comment]
Just when I start thinking that the project is in a stable condition you always manage to prove me wrong.

fixed in https://github.com/nkanaev/yarr/commit/9b178d1fb3fbb7dda2205dc2b0780dd5f6514e13.
