### ISSUE TITLE
Atom: URLs in <id></id> do not open

### ISSUE THREAD

**Issue by adaszko** [nkanaev/yarr#154]
Here we go again 😬 

The feed in question: https://dxuuu.xyz/atom.xml

It lacks a `<link>` element and puts the URL in `<id>`.  Yarr doesn't handle that well but [the feed passes validator checks](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdxuuu.xyz%2Fatom.xml).

**Comment by nkanaev** [comment]
This one, unfortunately, is not the parser's fault.

The feed is technically correct, but semantically is not. Atom feeds are expected to provide links in `<link>` element, and `<id>` is preserved for, well, unique identifier.

The only reason to treat it as a link would be to check whether other feed parsers do so to accommodate the common misusage. I've checked NetNewsWire, and it failed to extract link too.

**Comment by adaszko** [comment]
The Atom RFC uses the word "should" on <link> existence, not "must".

**Comment by adaszko** [comment]
Consequently, `<link>` is listed only as recommended, not required: https://validator.w3.org/feed/docs/atom.html

**Comment by nkanaev** [comment]
ah:

Element | Description
-- | --
id | Identifies the entry using a universally unique and permanent URI. Suggestions on how to make a good id can be found here. Two entries in a feed can have the same value for id if they represent the same entry at different points in time.<id>http://example.com/blog/1234</id>

recommendation from the link above. 

Will provide a fix shortly. Not sure how I feel about `Two entries in a feed can have the same value for id...` though, so will leave the implementation as it is.

**Comment by nkanaev** [comment]
fixed in https://github.com/nkanaev/yarr/commit/850ce195a01934135108f2e8dceb3797d22c9a3b.

@adaszko karma++

**Comment by adaszko** [comment]
Awesome! 🎉 🎉 🎉
