### ISSUE TITLE
GLIBC libraries are missing

### ISSUE THREAD

**Issue by hiBlunt** [nkanaev/yarr#155]
I download yarr v2.4 from github and unzip it on debian 11. when i run `./yarr -h`, it shows error as blow:
![missing](https://github.com/nkanaev/yarr/assets/21240907/52be5002-7dc9-4e8d-b15d-fd666c1725a4)
Obviously yarr needs static compilation. I will submit a PR to solve this problem later.

**Comment by nkanaev** [comment]
Provided the feedback in the PR.

**Comment by nicnab** [comment]
Same problem here! It's probably a noob question but how do I resolve this?
