### ISSUE TITLE
Flip of feed without time

### ISSUE THREAD

**Issue by lamescholar** [nkanaev/yarr#160]
Hello. When you generate RSS feed of a site, where you can't get a time of a post, and there are a lot of posts at one day, you still get chronologically accurate list of posts in rss file. But yarr flips it for some reason. For example, you got such rss file:

Post1
2023-09-30 00-00-00

Post2
2023-09-30 00-00-00

Post3
2023-09-29 00-00-00

Post4
2023-09-29 00-00-00

But in yarr you get an inverse for each day:

Post2
2023-09-30 00-00-00

Post1
2023-09-30 00-00-00

Post4
2023-09-29 00-00-00

Post3
2023-09-29 00-00-00

So, could you fix that, so feed doesn't flip? It complicates the reading.

For reproduction, here RSS feed of e-library ImWerden (https://imwerden.de/) generated with rss-bridge:

https://rss-bridge.org/bridge01/?action=display&bridge=XPathBridge&url=https%3A%2F%2Fimwerden.de%2F&item=%2Fhtml%2Fbody%2Fdiv%5B1%5D%2Fdiv%5B2%5D%2Fdiv%5B1%5D%2Fdiv%5B2%5D%2Fdiv%5Bposition%28%29%3E1+and+position%28%29%3C12%5D&title=.%2F%2Fdiv%5B4%5D%2Fh3&content=.%2F%2Fdiv%5B%40class%3D%22ArticleListItem-description%22%5D%2Fdiv%5B%40class%3D%22h6%22%5D&uri=.%2F%2Fdiv%5B4%5D%2Fh3%2Fa%2F%40href&author=&timestamp=substring-after%28string%28%2F%2Fdiv%5Bcontains%28text%28%29%2C+%22%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BE%3A%22%29%5D%29%2C+%22%3A+%22%29&enclosures=.%2F%2Fdiv%5B%40class%3D%22ArticleListItem-image%22%5D%2F%40style&categories=.%2F%2Fdiv%5B%40class%3D%22ArticleListItem-label%22%5D&format=Atom

**Comment by nkanaev** [comment]
fixed in https://github.com/nkanaev/yarr/commit/a895145586ad299bcd4072897f4fcd95fd0f69b9. thanks for the report!

**Comment by nkanaev** [comment]
the sorting is applied during storing articles, therefore existing feeds need to be readded for the fix to take place for old articles.
