### ISSUE TITLE
[BUG] Sometimes can't search content by characters?

### ISSUE THREAD

**Issue by scruel** [nkanaev/yarr#165]
![2023-10-24_16-35-39](https://github.com/nkanaev/yarr/assets/16933298/e919edd2-76ff-4cfd-9d7c-32db9debfdfc)
![2023-10-24_16-35-55](https://github.com/nkanaev/yarr/assets/16933298/27cd7844-d913-48e6-9344-0e408f607a12)

**Comment by nkanaev** [comment]
Search functionality is implemented via sqlite3's FTS4. It matches by terms and term prefixes, and doesn't seem to have substring matching capability.

For more, see: https://www.sqlite.org/fts3.html
