### ISSUE TITLE
Feature request: authentication

### ISSUE THREAD

**Issue by ilaer** [nkanaev/yarr#17]

**Comment by nkanaev** [comment]
thanks for the feedback. sorry, i don't speak your language. could you be more specific on the request?

**Comment by ilaer** [comment]
please add user login module。
default username:admin,pwd:admin.
after login,can change pwd.

**Comment by nkanaev** [comment]
authentication feature is likely to be shipped along with the Fever API.

in the meantime, consider using a proxy server which supports basic auth, like the one described in [here](https://lala.im/7402.html).

**Comment by ilaer** [comment]
> authentication feature is likely to be shipped along with the Fever API.
> 
> in the meantime, consider using a proxy server which supports basic auth, like the one described in [here](https://lala.im/7402.html).

it is plan b.
but it is enough.
thk.
