### ISSUE TITLE
Optimizations for large inventories

### ISSUE THREAD

**Issue by darkdragon-001** [nkanaev/yarr#175]
I have around 50 categories with around 1000 feeds - many of them in many categories.

In order to to make yarr usable and performant for this inventory, I suggest the following optimizations:
- Start with all categories collapsed.
- Only load the feeds of a category when uncollapsing it and free up memory when collapsing it.
- Only load list of articles for selected category/feed and free up memory when switching to another one.
  - Only refresh the list of articles pane when a feed which is part of the current view/filter is refreshed.
- Only load article once selected and free up memory when switching to another one.

Even for smaller inventories this should significantly reduce the memory overhead and speed things up there.

**Comment by nkanaev** [comment]
Thanks for the suggestion, but no.
