### ISSUE TITLE
Persist theme

### ISSUE THREAD

**Issue by darkdragon-001** [nkanaev/yarr#176]
Currently one has to change the theme every time one opens a new tab. It would be great if this setting was saved persistently.

**Comment by feddiriko** [comment]
And also for the login page, It would be great if the login page was the same theme as the rest.

**Comment by nkanaev** [comment]
The theme is persisted server-side. New tab picks up the correct theme. If you have multiple tabs open at the same time, simply refresh the pages after applying the theme.

I'll fix the login page theme.

**Comment by nkanaev** [comment]
fixed in https://github.com/nkanaev/yarr/commit/dc209320601a4d4f55f665349cc481755ec9f6a9.
