### ISSUE TITLE
Same feed in multiple folders/categories

### ISSUE THREAD

**Issue by darkdragon-001** [nkanaev/yarr#177]
When importing my big OPML file, I noticed some folders/categories being empty. As each feed has multiple categories, I expect them to have been added to other folders/categories already and skipping the additional ones.

This is supported both by OPML and Fever API.

**Comment by nkanaev** [comment]
Sorry, I don't quite follow. Can you provide an example OPML with the details of what you've expected/got?

**Comment by nkanaev** [comment]
If you meant tag-based approach (in contrast to hierarchical one) then I'm afraid that's not going to be added/supported.

**Comment by darkdragon-001** [comment]
Too bad, then yarr is unusable for me.
