### ISSUE TITLE
support http proxy

### ISSUE THREAD

**Issue by ilaer** [nkanaev/yarr#18]
hope to support http proxy.
thk.

**Comment by nkanaev** [comment]
needs a clarification

**Comment by ilaer** [comment]
our network can not reach some url,like google.com,reddit.
so i  use http proxy to get reddit rss.
hope  yarr  support http proxy.

**Comment by e-zk** [comment]
If you export the environment variable `$HTTP_PROXY` with your proxy url+port, `net/http` will use that for requests:

```
export HTTP_PROXY="https://example.com:8118"
./yarr
```

This should work provided all network requests are sent via `net/http`. @nkanaev : would that be correct?

**Comment by nkanaev** [comment]
i could add the feature to set proxy parameter in the UI itself, but for me personally it doesn't make sense from usability perspective.

*yarr* is designed to work within/along with the browser, hence if *yarr* can access blocked content (with proxy set), but the browser cannot (without proxy set), it's more convenient to configure proxy on the OS-level, or use other means (VPN, Lantern etc.) for circumvention.

If you still prefer to set proxy on per-app basis, please consider using what @e-zk has suggested. proxying can be configured by setting `HTTPS_PROXY`/`HTTP_PROXY`/`NO_PROXY` env. variables.
