### ISSUE TITLE
Refresh single feed

### ISSUE THREAD

**Issue by lamescholar** [nkanaev/yarr#180]
Hello. Sometimes when I refresh the feeds, couple of feeds have an error. I have a lot of feeds, so I don't want to refresh all of them again for sake of couple of feeds with an error. Would you add an option to refresh single feed?

**Comment by nkanaev** [comment]
What are the errors you get that are resolved by refreshing?

In my experience, most of the partial errors are the ones that require manual intervention (feed gone, malformed, rate-limiting etc), which are not resolved simply by refreshing it.

**Comment by lamescholar** [comment]
Sometimes it's куфддн RSS malfunction. But in some cases, it just takes some time for a feed to load. I guess, there is a time limit when all feeds are refreshing. If you delete such feeds and add them again - they load.

**Comment by nkanaev** [comment]
Yes, there's a request timeout. I can adjust it, given that you could provide me timing details for the working feed urls (see [here](https://blog.josephscott.org/2011/10/14/timing-details-with-curl/) for an example on how to do that).

**Comment by lamescholar** [comment]
https://newtimes.ru/rss/
This feed is loading slowly from time to time. At the moment it takes 23s to load (I used curl method you provided). I don't think it's a good idea to raise overall time limit, because, if bunch feeds actually don't work, they will slow down the process. It is better to introduce refreshment of single feed with prolonged time limit.

**Comment by nkanaev** [comment]
Sorry, I'll have to say no to that. That's a feature and I'm trying to keep the app functionality limited as stated in https://github.com/nkanaev/yarr/issues/57.

**Comment by kqvanity** [comment]
@nkanaev I do get the design decisions you're making, but how one could deal for example with scalability. Currently have 400 feeds and it's only gonna grow

**Comment by bestlzk** [comment]
@lamescholar @kqvanity  I encountered the same problem. Is there any RSS reader that supports single feed refresh?

**Comment by kqvanity** [comment]
@bestlzk  I suppose goread does support it, but I didn't like it UX & TUI.

**Comment by bestlzk** [comment]
> @bestlzk I suppose goread does support it, but I didn't like it UX & TUI.

Thank you, I don’t like its TUI too, I found feedbro can meet my needs

**Comment by kqvanity** [comment]
@bestlzk yw. I personally don't like to use a browser extension (especially with the whole caching thing). You can give feedBro a try as well!
