### ISSUE TITLE
Navigate from news item to feed

### ISSUE THREAD

**Issue by tarasglek** [nkanaev/yarr#181]
At the moment I can't click on "DoItHub Blog" in article view. To open it in sidebar(eg to mark entire feed as read or to remove it). Would be nice to be able to do that instead of having to use browser search function to find the feed in sidebar
<img width="1045" alt="image" src="https://github.com/nkanaev/yarr/assets/857083/44987dc7-ea2c-4f5d-84a6-31db43cfa789">

**Comment by nkanaev** [comment]
Nice suggestion. Will try to incorporate it to the upcoming release.

**Comment by nkanaev** [comment]
implemented in https://github.com/nkanaev/yarr/commit/4983e18e23b34126e778c2e56e684f9f8d801f2b.
