### ISSUE TITLE
Invidious feeds not working

### ISSUE THREAD

**Issue by xfzv** [nkanaev/yarr#182]
```console
% yarr -version
v2.4 (259474ca)
```

Steps to reproduce:
1. Try to add any Invidious ~~or Piped~~ feed, e.g. `https://yewtu.be/feed/channel/UC5UAwBUum7CPN5buc-_N1Fw` ~~or `https://pipedapi.kavin.rocks/feed/unauthenticated/rss?channels=UC5UAwBUum7CPN5buc-_N1Fw`~~
2. With Invidious feeds, the following error is displayed: `No feeds found at the given url.`. ~~For Piped feeds, the spinning wheel is displayed indefinitely after clicking on `Add`.~~

I tried with several instances but it doesn't make any difference. YouTube feeds work fine.

---

Edit: I've just tried with master, same behavior:

```console
% yarr -version
v2.4 (9d5b8d99)
```

---

Edit 2: Turns out Piped feeds actually work after restarting `yarr`. Log file shows the following regarding Invidious feeds:

```
2024/03/17 09:46:27 routes.go:235: Faild to discover feed for https://yewtu.be/feed/channel/UC5UAwBUum7CPN5buc-_N1Fw: status code 429
```

**Comment by nkanaev** [comment]
That's not an issue on *yarr's* end - the server is rate-limiting you (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).
