### ISSUE TITLE
Build failure on alpine 3.19

### ISSUE THREAD

**Issue by Orhideous** [nkanaev/yarr#187]
See: https://github.com/mattn/go-sqlite3/issues/1164

Possible workaround is pinning build image to `golang:alpine3.18` in [etc/dockerfile](https://github.com/nkanaev/yarr/blob/master/etc/dockerfile)

**Comment by nkanaev** [comment]
done in https://github.com/nkanaev/yarr/commit/c896f779b5661e717666847dc246218ef575b42f.
