### ISSUE TITLE
[bug] RSS feed with math/latex displayed wrong

### ISSUE THREAD

**Issue by k4lizen** [nkanaev/yarr#192]
This post: https://codahale.com//towards-a-safer-footgun/
In reader:
![image](https://github.com/nkanaev/yarr/assets/124312252/44f098c4-d3f9-41d9-ab4b-3be298ee8f09)
On website:
![image](https://github.com/nkanaev/yarr/assets/124312252/f4f4c7ac-3148-4cbe-96c1-b89487409233)
This makes the blog post unreadable

**Comment by nkanaev** [comment]
TeX is not part of HTML spec. The website is using JS to convert TeX to HTML. *yarr* can display only what feed source is sending, in this case plain TeX will be shown as is.

**Comment by k4lizen** [comment]
Okay
