### ISSUE TITLE
HTML is not escaped when displayed outside of "Read Here" mode

### ISSUE THREAD

**Issue by toBeOfUse** [nkanaev/yarr#198]
Simon Willison recently made [a post](https://simonwillison.net/2024/Apr/30/approach-to-html-web-components/) that included some HTML in its text:

![image](https://github.com/nkanaev/yarr/assets/49729978/ef163d43-3e8c-4bbf-a6e4-09c781f9ce22)

In normal Yarr, this is placed in the page as actual HTML, so the content can't be read on the actual page:

![image](https://github.com/nkanaev/yarr/assets/49729978/9b0b95f7-427b-4f26-9e3d-91a39c73c7d9)

In "Read Here" mode, this problem is fixed:

![image](https://github.com/nkanaev/yarr/assets/49729978/56bd7162-d391-47fe-90b6-06537087857f)

I will also note that I'm not actually sure what "Read Here" mode is intended for - it being on or off doesn't seem to make much of a difference for the posts I see.

**Comment by dbr** [comment]
Trimmed down version of the feed with the problem:

```
<?xml version="1.0" encoding="utf-8"?>
<feed xml:lang="en-us"
	xmlns="http://www.w3.org/2005/Atom">
	<title>Simon Willison's Weblog</title>
	<link href="http://simonwillison.net/" rel="alternate"/>
	<link href="http://simonwillison.net/atom/everything/" rel="self"/>
	<id>http://simonwillison.net/</id>
	<updated>2024-05-05T14:08:01+00:00</updated>
	<author>
		<name>Simon Willison</name>
	</author>

	<entry>
		<title>My approach to HTML web components</title>
		<link href="https://simonwillison.net/2024/Apr/30/approach-to-html-web-components/#atom-everything" rel="alternate"/>
		<published>2024-04-30T11:02:48+00:00</published>
		<updated>2024-04-30T11:02:48+00:00</updated>
		<id>https://simonwillison.net/2024/Apr/30/approach-to-html-web-components/#atom-everything</id>
		<summary type="html">
&lt;p&gt;&lt;a href="https://adactio.com/journal/21078"&gt;My approach to HTML web components&lt;/a&gt;&lt;/p&gt;
Some neat patterns here from Jeremy Keith, who is using Web Components extensively for progressive enhancement of existing markup.&lt;/p&gt;
&lt;blockquote&gt;
&lt;p&gt;The reactivity you get with full-on frameworks [like React and Vue] isn’t something that web components offer. But I do think web components can replace jQuery and other approaches to scripting the DOM.&lt;/p&gt;
&lt;/blockquote&gt;
&lt;p&gt;Jeremy likes naming components with their element as a prefix (since all element names must contain at least one hyphen), and suggests building components under the single responsibility principle - so you can do things like &lt;code&gt;&amp;lt;button-confirm&amp;gt;&amp;lt;button-clipboard&amp;gt;&amp;lt;button&amp;gt;...&lt;/code&gt;.&lt;/p&gt;
&lt;p&gt;Jeremy configure buttons with &lt;code&gt;data-&lt;/code&gt; attributes and has them communicate with each other using custom events.&lt;/p&gt;
&lt;p&gt;Something I hadn't realized is that since the &lt;code&gt;connectedCallback&lt;/code&gt; function on a custom element is fired any time that element is attached to a page you can &lt;code&gt;fetch()&lt;/code&gt; and then &lt;code&gt;insertHTML&lt;/code&gt; content that includes elements and know that they will initialize themselves without needing any extra logic - great for the kind of pattern encourages by systems such as &lt;a href="https://htmx.org/"&gt;HTMX&lt;/a&gt;.
</summary>
		<category term="webcomponents"/>
		<category term="jeremykeith"/>
		<category term="progressiveenhancement"/>
		<category term="javascript"/>
	</entry>
</feed>
```

> I will also note that I'm not actually sure what "Read Here" mode is intended for - it being on or off doesn't seem to make much of a difference for the posts I see.

The Read Here mode is useful for feeds which don't contain the full article (e.g a snippet or just the link to webpage)
An example feed would be https://lobste.rs/rss which without Read Here just shows the "Comments" link, and with shows the full linked article

**Comment by toBeOfUse** [comment]
> The Read Here mode is useful for feeds which don't contain the full article (e.g a snippet or just the link to webpage)

Interesting, thank you. I only have one feed that acts like that, which I didn't test this on. Probably not worth opening an issue for, but maybe "Read Here" could be renamed to something like "Retrieve All Content"

**Comment by nkanaev** [comment]
Seems like a bug to me. The code section of the original feed entry is properly escaped, yet is decoded and is turned into html element. So this in the feed's part:

    &lt;code&gt;&amp;lt;button-confirm&amp;gt;&lt;code&gt;

should be stored as:

    <code>&lt;button-confirm&gt;<code>

in the backend, which will appear as:

    <button-confirm>

in the UI. But instead it's stored as:

    <code><button-confirm><code>

which implies that parsing is probably not working correctly.
