### ISSUE TITLE
Feature Request: Make appindicator/gtk optional

### ISSUE THREAD

**Issue by eldridgea** [nkanaev/yarr#2]
That would allow yarr to be built and run headless on linux.

(Loving this so far though!)

**Comment by nkanaev** [comment]
thanks for the suggestion. i've got it planned already

**Comment by e-zk** [comment]
If you don't mind me asking, what are your plans for doing this?

I had an idea:  
`cmd/gui/main.go` for the current/GUI app  
`cmd/headless/main.go` for the headless variant  

Through additional make targets this can be as simple as going `make build_linux_headless` to build the headless variant on Linux, for example.

**Comment by nkanaev** [comment]
My current priority is to get prebuilt binaries for macos & windows.

I initially intended to use it on Linux (my personal laptop) with GUI (tray icon) support too, but soon came to realise that Linux is quite a wild land.

* Other lib requirements (https://github.com/getlantern/systray#linux) which, probably, leads to:
* Packaging for different Linux distros/versions.
* Various Idiosyncrasies (my goto os, elementary, doesn't display 3rd party icons)

I'm not an expert on Linux desktop, so I'm open to any suggestions.

My suggestion for now would be to ignore the GUI part for Linux altogether, which would result in `make build_linux` generate binary without the GUI dependency.

**Comment by nkanaev** [comment]
maybe have `cmd/yarr/main.go`, `cmd/yarr/gui.go` & `cmd/yarr/gui_headless.go`, which would contain stub functionality for headless mode?

**Comment by eldridgea** [comment]
Sure! I tend to run my services out of Docker containers on a headless so being able to Dockerize this was my main plan. Dockerizing it against the golang base container seems to work fine currently other than the systray part.

I think your plan of ignoring the GUI part for Linux altogether makes the most sense personally. I'll confess I haven't used a Linux desktop as my daily driver in a while, but in general I didn't expect systray icons for running services like this and would run it from systemd (which is what elementary uses AFAIK). 

My golang skills are effectively nonexistent, but if `make build_linux`, `cmd/headless/main.go`, or some variant exists, I'd be happy to take on working on a script/documentation to take care of the systemd parts and write the Dockerfile too if either/both of those things would be helpful?

**Comment by nkanaev** [comment]
I've removed tray icon support from Linux altogether for now (https://github.com/nkanaev/yarr/commit/439d98003f25e512a378fee4e23aea8a0f36b971). would be happy if anyone could test it.

**Comment by nkanaev** [comment]
@eldridgea thanks for your support. feel free to create the docs in the [wiki](https://github.com/nkanaev/yarr/wiki).
