### ISSUE TITLE
Bug: Unintended player showing up in feed content

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#207]
The image on the left is YARR, which displays the unintentional player compared to the RSSPREVIEW extension.

![image](https://github.com/nkanaev/yarr/assets/19629778/abf4fb93-c9d7-478e-beee-21e33ee76ef8)

Feed: https://rssbridge.flossboxin.org.in/?action=display&bridge=FirefoxReleaseNotesBridge&platform=&format=Atom
XML: [xml.zip](https://github.com/user-attachments/files/15791129/xml.zip)

**Comment by nkanaev** [comment]
fixed in https://github.com/nkanaev/yarr/pull/206
