### ISSUE TITLE
HTTP/SOCKS support

### ISSUE THREAD

**Issue by macruspareto** [nkanaev/yarr#208]
Hello author!

Thanks for making Yarr happen!
I was searching around git for a small and simple RSS reader and found it.
It serves its purpose flawlessly!

Could you add the support for HTTP/SOCKS proxy in future versions?

You have suggested setting the env variable HTTP_PROXY
It seems to work on Linux but is being completely ignored on Windows
(tried it multiple times).

I think adding proxy support should not be difficult. 20-30 lines of code maximum.

There's a Go library for that:

https://github.com/elazarl/goproxy

Many thanks!

PS: Or perhaps someone who knows Go could post a piece of code here and we compile it ourselves.

**Comment by nkanaev** [comment]
I do not plan to add proxy support in the UI. Please use the env variable support that Golang provides.

You can ask the setup guide for Windows in [Github Discussions](https://github.com/nkanaev/yarr/discussions) or elsewhere (StackOverflow, Reddit etc). Unfortunately I'm unable to help you with that as I don't use Windows.
