### ISSUE TITLE
feeds not continuzing to lazy load remaining content on single-pane view

### ISSUE THREAD

**Issue by kqvanity** [nkanaev/yarr#211]
normally when I'm scrolling in two-pane view, yarr would lazy load the remaining content, however when on a single-pane, it only loads what was initially loaded. For that, I have to revert back scroll a bit to load the remaining content, figure out at which list item I was at (not highlighted by default when returning from one-page view), then continue on, and so on.

**Comment by nkanaev** [comment]
duplicate of https://github.com/nkanaev/yarr/issues/209
