### ISSUE TITLE
[BUG] There are many articles in the XML file, but only one was actually added.

### ISSUE THREAD

**Issue by hoyii** [nkanaev/yarr#215]
## Reproduction

Click the "New Feed" button, enter the RSS subscription: https://v2ex-create.nexmm.com/rss.xml, and click the Confirm button. Once added successfully, only the first article will be displayed:
![image](https://github.com/user-attachments/assets/5753ef44-586c-4906-bc0a-dfb7c878bbe0)

## Possible Causes

I reviewed the source code, and the FeedID and GUID of this RSS subscription are both empty.So, an ID conflict occurred, which resulted in the inability to write article information into the database:
![image](https://github.com/user-attachments/assets/a731f8c4-13e5-47b9-8d86-18c5f7c64fdf)

I suspect there is an issue with the judgment here, because this XML file does not have a URL as its GUID
![image](https://github.com/user-attachments/assets/8ffe8992-c797-4462-81f7-5d477c5cfb56)

Or is it a problem with the format of RSS subscriptions themselves? I'm not sure about this.

If possible, I hope you can provide some ideas for me to modify the code. Thank you!

**Comment by nkanaev** [comment]
@hoyii thanks for reporting. That's a bug. BothGUID and URL are  stated as optional in the spec.

I think the best approach would be to fallback to a hash of combination of other uniquely identifiable elements (title, date and maybe content).

**Comment by nkanaev** [comment]
fixed in https://github.com/nkanaev/yarr/commit/e9cbea500b08f6401b6d83747bd94210a83db68e
