### ISSUE TITLE
Images Not Displaying in Feeds

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#223]
Images from the PSA feeds are not displaying in Yarr, but they work fine in other feed readers. Kindly check:

- https://psa.wf/category/movie/feed/
- https://psa.wf/category/tv-show/feed/

**Comment by nkanaev** [comment]
fixed in https://github.com/nkanaev/yarr/commit/223039b2c66fbdcdeedc2bc7280bfe72ccdd4a06
