### ISSUE TITLE
In addition to importing/exporting .opml files, consider support using a specific .opml file as a source of truth.

### ISSUE THREAD

**Issue by matklad** [nkanaev/yarr#23]
I'd love to store my feeds in my dotfiles repository: [feeds.opml](https://github.com/matklad/config/blob/400c597092d9f52b0d88fda74fdcddbc87458c9d/home/.local/share/akregator/data/feeds.opml). Currently, I use akregator to do this. The feed list just an akregator's config file, and is updated when I add/remove feeds. 

If yarr had a similar feature, I would consider switching to it ;) Especially if was able to canonicalize xml before writing the file out: akregator loves to just permute xml attributes without semantic changes, which makes storing this file in git pretty annoying.

**Comment by nkanaev** [comment]
sorry, there are no plans to use external files as the feed source.

the only thing i could suggest is to automate feed importing/exporting via api:

```sh
curl http://localhost:7070/opml/export > /path/to/feeds.xml
curl http://localhost:7070/opml/import -X POST -F 'opml=/path/to/feeds.xml'
```
