### ISSUE TITLE
Suggestion: Keyboard Shortcuts

### ISSUE THREAD

**Issue by epmills** [nkanaev/yarr#25]
How would you feel about the idea of adding keyboard shortcuts?  I find them very handy in NetNewsWire.
Not asking you to necessarily do the implementation; more curious about your opinion of the capability.

**Comment by nkanaev** [comment]
I think that's a great idea. I personally never use shortcuts, but I'm happy to assist anyone who's willing to implement the feature.

**Comment by Duarte-Dias** [comment]
I'm willing to implement this :)  can you build a list of shortcuts that should be added? (and their corresponding keys)

**Comment by epmills** [comment]
Thanks, @Duarte-Dias.  My thoughts were to align as closely as possible with [those from NetNewsWire](https://ranchero.com/netnewswire/help/mac/5.0/en/keyboard-shortcuts).

Question: Should the shortcut definitions be segregated from the existing UI markup?  This could allow shortcuts to be optionally attached to the UI rather than hardcoded.  Additionally, there could be multiple "shortcut sets" from which the user could select (or none).  I was positing using [StimulusJS](https://stimulus.hotwire.dev/handbook/introduction) to attach the shortcuts (both the hint text and event listener).

What are your thoughts?

**Comment by nkanaev** [comment]
feel free to come up with any shortcuts that you find ergonomic, as long as it doesn't clash with the current browser behaviour (arrow keys, tabs etc.).

i like the idea of hardcoded shortcuts (feel free to elaborate/discuss/disagree with me on that). hardcoded keys makes it easier to document/implement the feature.

keyboard handlers can be done via vanilla js, introduce 3rd party libraries only if necessary.

**Comment by nkanaev** [comment]
@Duarte-Dias 's changes were merged onto master, with some changes & fixes. expect the feature in v1.4

**Comment by Duarte-Dias** [comment]
@nkanaev thanks for picking it back up, I've been busy with work and other projects
