### ISSUE TITLE
Reverse proxy behind non-root path

### ISSUE THREAD

**Issue by maghoff** [nkanaev/yarr#26]
I have set up yarr behind reverse proxy on a non-root path. For illustration, it could be `http://example.com/my/yarr/`. The HTML seems to refer to resources by relative path (`./static/...`), but particularly [api.js](https://github.com/nkanaev/yarr/blob/master/assets/javascripts/api.js) seems to refer to absolute paths, such as `/api/feeds/...`. These URLs are then resolved to `http://example.com/api/feeds/...`, which is not where my yarr instance is found.

I request that yarr supports being proxied behind a non-root path like I have set up.

It is possible to implement this by making all URLs used fully relative. A common alternative is to take the root address as a configuration input (i.e. `root = http://example.com/my/yarr/`) and use that to generate fully absolute URLs.

**Comment by nkanaev** [comment]
The usage of relative paths (in html) and absolute paths (in js) is accidental - html template came first as a design draft and the api was implemented later.

I personally don't like the idea of using relative paths, so my suggestion would be to host it on a different port or a subdomain, if possible. However, I understand the proposed usage is justifiable.

One of the solutions I could think of would be to create a `-base` parameter. For ex, if it's run as `yarr -base "/my/yarr"`, it would serve only on "127.0.0.1/my/yarr" and all the links will be prefixed with the base url.

**Comment by michaeljmcd** [comment]
This would definitely be helpful. I set up Yarr on my web server today and setup a separate subdomain + nginx proxy to get it all working. That said it's working great so far!

**Comment by nkanaev** [comment]
implemented by @hcl. the feature is available in `master` branch. will be shipped in `v1.2`
