### ISSUE TITLE
proxy configuration

### ISSUE THREAD

**Issue by ilaer** [nkanaev/yarr#27]
![image](https://user-images.githubusercontent.com/5914968/99024688-0bedde00-25a2-11eb-9397-47fe180b4bb6.png)
[quiterss](https://quiterss.org/)　can setting proxy, hope yarr too.

**Comment by e-zk** [comment]
You can use the `HTTP_PROXY` environment variable to set a proxy server for yarr to use. 
This has been mentioned before in #18; there is no desire at this time for the creator to implement a proxy configuration UI.

[Here](https://stackoverflow.com/questions/14661511/setting-up-proxy-for-http-client/14663620#14663620) is some more info on how to do that.

**Comment by nkanaev** [comment]
Sorry @ilaer, I have no interest in adding settings page. If you'd like to setup http proxy, you can do so as @e-zk suggested.
