### ISSUE TITLE
Feature: Ability to mark "all older than n days" as read

### ISSUE THREAD

**Issue by iliafrenkel** [nkanaev/yarr#34]
It will be nice to have an option (or several options) to mark all entries older than a certain amount of days as read.

**Example use case**
You go on holidays, camping or something similar. You come back after a week and some of the items in the feeds are now obsolete.

**Comment by nkanaev** [comment]
@iliafrenkel sorry, but i'll have to say no to the feature. the proposal sounds compelling, but the rejection is personal: i'd like to keep the application light on settings.

**Comment by iliafrenkel** [comment]
Fair enough.
