### ISSUE TITLE
Login page empty

### ISSUE THREAD

**Issue by einschmidt** [nkanaev/yarr#37]
# Problem

When starting yarr with the parameter -auth-file, the expected login page remains empty.

# Run call

```
/usr/local/bin/yarr -addr 127.0.0.1:7070 -db /data/yarr.db -auth-file /share/yarr/auth
```

# Version
I am using version v1.2

# Reason?

Uncertain here, but the makefile doesn't include the login.html for the assets. Or is my run call wrong?

**Comment by nkanaev** [comment]
@einschmidt thanks for the report! fixed in https://github.com/nkanaev/yarr/commit/26313f78427b758ed3d4135a8cb87cc81e2dedd1, the new version will go out soon.
