### ISSUE TITLE
Articles are unread if deleting folder

### ISSUE THREAD

**Issue by fossdd** [nkanaev/yarr#39]
I've removed a folder with 2 feeds inside. I complete read the 2 feeds. After deleting the folder all articles are marked as unread

**Comment by nkanaev** [comment]
@fossdd i couldn't reproduce the issue by the description you've provided.

would you be able to provide a recording of the bug, if it's still reproducible on your end?

**Comment by fossdd** [comment]
Oh, you're right. I can't repoduce that, too. I guess this was once again a system error that my local file system was read-only. 😅
