### ISSUE TITLE
Suggestion: Podcasts

### ISSUE THREAD

**Issue by aboutDavid** [nkanaev/yarr#40]
Hey sorry if this isn't the right place to ask for suggestions, but I think podcasts would be a nice addition to yarr. Normally they would be in the XML tag enclosure. 

```xml
<enclosure length="[LENGTH, eg 26546304]" type="audio/mpeg" url="[URL]"/>
```

**Comment by nkanaev** [comment]
it's on my todo list. expect it on the next release.

**Comment by aboutDavid** [comment]
Thanks!

**Comment by nkanaev** [comment]
commit https://github.com/nkanaev/yarr/commit/e1cfb04f98af2a6dccce7791051d8a8a8022e706 adds support for podcasts. the update will be rolled out in v1.4

if there are feeds with podcasts in the database already, they must be readded for audio to appear in the older articles.
