### ISSUE TITLE
Setting to remove Reading pane

### ISSUE THREAD

**Issue by maxperron** [nkanaev/yarr#41]
Hello! Thank you for this project, it's very nice!

Would you think it's possible to add a setting to remove the reading pane?

**Comment by nkanaev** [comment]
thanks!

unfortunately, the ui is unlikely change for the foreseable future, but i'll keep that in mind (see [rationale](https://github.com/nkanaev/yarr/blob/d39bdd7ef236633bd8ba8c9d2ec07be09ea3fb9d/doc/rationale.txt#L29-L43))
