### ISSUE TITLE
Youtube feed preview not working

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#42]
YouTube feeds showing empty screen.

https://imgur.com/a/SlJ3J2S

**Comment by nkanaev** [comment]
thanks for the suggestion.

feed reader/processor needs to be updated to present the media content in the absence of the primary content.

can't guarantee it'll be coming soon, but will definitely be implemented.

**Comment by nkanaev** [comment]
the feed parser was rewritten to fetch media content. this includes youtube feeds as well. youtube iframe is shown when "read here" is clicked.

expect the feature in v2.
