### ISSUE TITLE
Any method to install via docker

### ISSUE THREAD

**Issue by starsareintherose** [nkanaev/yarr#43]
Any method to install via docker?

**Comment by verahawk** [comment]
Do you mean desktop version or self-hosted app? For the latter you should use `dockerfile` to build an image locally.

**Comment by nkanaev** [comment]
docker installation has to be done locally as @verahawk has suggested (see the `build` section of readme).

there is no supported docker image at the moment. see the discussion here: https://github.com/nkanaev/yarr/issues/20

**Comment by nkanaev** [comment]
https://nkanaev.github.io/yarr/en/installation/docker/
