### ISSUE TITLE
Request: Keyboard Shortcuts to browse an article content

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#45]
Like UP and DOWN arrow to browse an article content.

**Comment by nkanaev** [comment]
UP/DOWN keys will clash with the default browser behaviour.

being able to scroll the content sounds reasonable. need to come up with the suitable keybindings though. i'm open to suggestions.

**Comment by tillcash** [comment]
**n** / **p** : Move down / up article content.

Some of common keyboard shortcuts

**shift + a** : Mark all as read
**shift + r** : Manual refresh all feeds in background
**m :** Mark selected item as read / unread
**s** : Mark selected item as starred / unstarred
**r** : Extract full content or readability or read here
**a** : Add feed
**l** & **→** / **h** & **←** : next / prev feed
**j** & **↓** / **k** & **↑** : next / prev article
**o** : open an article's link
**shift + o** : open an article's link in background
**shift + p** : Preferences
**?** : Keyboard shortcuts list

**Comment by tillcash** [comment]
**w** or **shift + w** : Close article content
**t** : Toggle theme

**Comment by nkanaev** [comment]
let's limit the scope of keyboard shortcuts for now:

i'd like to treat them as the common operation alternatives (navigation & marking), not the full interaction substitution. the latter should be rather implemented as an accessibility feature.

`f` / `b` imho feels like a good option for scrolling articles (forward/backwards) similar to `less` shortcuts.

**Comment by tillcash** [comment]
f / b is also fine. One thing to consider n /p is near to hjkl which is already assigned to movement.

**n** / **p** : Move dow**n** / u**p** article content.

However, thanks for considering my request.

**Comment by nkanaev** [comment]
article scroll keybindings added in https://github.com/nkanaev/yarr/commit/721de3fba6a9928849bb2963e1fb80965e94b50e. expect the feature in v1.5
