### ISSUE TITLE
Raspberry Pi | ARM Support

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#51]
Could you provide the build for Raspberry Pi?

**Comment by nkanaev** [comment]
all the builds are done via github actions. github provides runners only for windows/macos/linux.

sorry, can't help you with that. consider compiling it from scratch.

**Comment by hmsjy2017** [comment]
@nkanaev But we can connect self-hosted runners (such as Raspberry Pi) to GitHub Actions.
