### ISSUE TITLE
Showing date as January 1, 1970 might be bug.

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#52]
https://old.reddit.com/r/TechNewsToday.rss

![Screenshot_2021-04-02 yarr (102)](https://user-images.githubusercontent.com/19629778/113393039-b466d800-93b3-11eb-840a-451aa06ea8a3.png)

**Comment by nkanaev** [comment]
could reproduce it this morning, but the issue seems to be gone now. could be reddit's fault.
can you confirm it by deleting/adding the feed again?

**Comment by tillcash** [comment]
Issue fixed after re-adding the feed. 
Is there any future plans to allow editing the feed URL?

**Comment by nkanaev** [comment]
no, editing the feed url is not planned.
