### ISSUE TITLE
Can't recognize rss feeds when the response type is only application/xml

### ISSUE THREAD

**Issue by minioin** [nkanaev/yarr#6]

**Comment by nkanaev** [comment]
could you elaborate on this? what are the links affected?

**Comment by minioin** [comment]
For example, [this one](https://www.pcworld.com/index.rss).

**Comment by nkanaev** [comment]
thanks for the report.

fixed in the dependent repo: https://github.com/nkanaev/gofeed. consider getting the latest changes.
