### ISSUE TITLE
Extract full content by default

### ISSUE THREAD

**Issue by sevospl** [nkanaev/yarr#60]
Hi! First off, thanks a ton for the project. It's dead easy to install and use - loving this a lot! Please, keep it up and never overcomplicate things like others tend to do.

I would very much appreciate the ability to set auto extract full content for certain feeds so that the experience is more immersive. Instead of having to manually click "Read Here" it'd be done by default.

BTW: I'd have one more little feature request related to scroll bar (specifically hiding it for the articles part). I believe it's trivial to implement and would look much better.

Thanks again!

**Comment by nkanaev** [comment]
@sevospl thanks!

> set auto extract full content

i do understand the need, given that there are certain feeds with empty bodies. however, i'll have to say no to that.
the use case is relatively rare and doesn't justify the development time. `read here` is meant to be a fallback/supplementary feature for accessing content, which is inferior to just opening the url in a new tab (and using a browser's readability plugin).
for those who use `read here` feature often, there is a keyboard shortcut for that.

> feature request related to scroll bar (specifically hiding it for the articles part)

i considered styling scrollbars, but decided to stick with the native ones. if the scrollbars provided by the os is unsatisfactory, i'd recommend installing an extension (i believe most browsers provide that).

**Comment by bt4ibwem8** [comment]
`read here` should be remembered by yarr, the same as yarr does remember other settings (selected theme for example).
So if i click on `read here` on some article, yarr would remember it just for this specific rss source. So everyone would to make customized rules. Many rss sources do not load full text unfortunately...
