### ISSUE TITLE
Steam - Youtube embedded player size is small

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#61]
Increase YouTube embedded player size in Steam feed. Also clicking 'Read Here' shows nothing.

https://steamcommunity.com/games/1073910/rss/

![yarr](https://user-images.githubusercontent.com/19629778/117874065-2c32f700-b2be-11eb-86fe-0aec66e822e1.png)

**Comment by nkanaev** [comment]
video size fixed in https://github.com/nkanaev/yarr/commit/28f08ad42af2a25e7447b9956c9afa2233e32b47. expect in v2.1.

unfortunately `read here` won't be able to scrape the content - the steam pages use client-side rendering.
