### ISSUE TITLE
Pagination does not fetch the correct articles after some are marked as read

### ISSUE THREAD

**Issue by Farow** [nkanaev/yarr#63]
In the unread section, when you scroll down after reading a few articles some of them will not show up.

I could take a shot at trying to fix it and I've thought of two ways this can be fixed.

- The web-ui could request items from a specific offset (instead of by page), which would get decreased for each article read.
- The web-ui could request items after the last item in the list, similar to how reddit handles pagination. This would to somewhat alter the query.

Any thoughts as to which would be better, or maybe a different solution?

Lastly, in rare cases the unread counter can go below 0. I haven't been able to reproduce it consistently and I don't know if it's related to this specific issue. Have you noticed that at all?

**Comment by nkanaev** [comment]
nice catch.

i like the 2nd approach. i'd completely ditch the `page` param and introduce `after` that takes the last item's id instead.

**Comment by Farow** [comment]
I think I may have figured out when the counter issue happens. If you switch to unread from starred/all and new articles have been added, they're displayed in the article list but the counters seemingly remain the same as before. I haven't tested this thoroughly but it looks like a separate issue overall.

Those shouldn't be too difficult to fix but I likely won't be able to work on it until the weekend.

**Comment by nkanaev** [comment]
the pagination was (hopefully) fixed in https://github.com/nkanaev/yarr/commit/7aeb458ee5dc833dbab28a9787b5352e96078bfb.

as of the counters - when the autorefreshing is turned on or feed refreshing is triggered in another tab/browser, the original page will display the values unchanged.

currently there's no mechanism to keep the stats in sync. i couldn't come up with a simple solution for that so decided to leave it as it is.

**Comment by Farow** [comment]
Wouldn't adding `.then(this.refreshStats.bind(this))` on line 304 update the counters when switching filters?

https://github.com/nkanaev/yarr/blob/58f4e1f6c99c764e09943d4b2c663af746448915/src/assets/javascripts/app.js#L304

**Comment by nkanaev** [comment]
only for one use case. if the feeds get refreshed while a user is skimming through the articles without changing filters, the stats will stay as it is.

the proper fix requries either:

- rethinking the stats mechanism (haven't come up with an easy solution for that)
- introducing bidirectional client-server state management (don't like the implementation complexity)

**Comment by Farow** [comment]
> if the feeds get refreshed while a user is skimming through the articles without changing filters, the stats will stay as it is.

Don't the feeds only get refreshed on the server side and fetched only if the user changes filters? I've had the refresh option at 10 minutes but it doesn't reload feed items automatically on the client. I don't think the counter discrepancy happens in any other situations.

In any case, thanks for the quick fix on pagination.
