### ISSUE TITLE
No feeds found at the given url.

### ISSUE THREAD

**Issue by tillcash** [nkanaev/yarr#64]
https://www.smarthomebeginner.com/feed/

Getting "No feeds found at the given url." error even-though its accepting in  QuiteRSS and Feedbro extension.

**Comment by nkanaev** [comment]
appears to be cloudflare captcha security measures:

```
$ curl -s https://www.smarthomebeginner.com/feed/ | head -n 10
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title>Please Wait... | Cloudflare</title>
  
<meta name="captcha-bypass" id="captcha-bypass" />
```

also see here: https://community.cloudflare.com/t/cloudflare-blocking-some-feed-readers-from-accessing-armenian-rss-feeds/226111/3

sorry, not much that i can do. probably must be resolved on the provder's side (the website owner).
