### ISSUE TITLE
How to make it into a deb package?

### ISSUE THREAD

**Issue by hmsjy2017** [nkanaev/yarr#65]
I prefer deb packages to binary files. Because it is easier to install and update.

**Comment by nkanaev** [comment]
1. *yarr* is a single zipped binary. installation is a simple process (`curl`, `unzip` & `mv`)
2. *yarr* is a side project. packaging & distribution is cumbersome and not fun. anyone is welcome to package & promote it (deb, rpm, pkg etc)
