### ISSUE TITLE
Potential features in a branch

### ISSUE THREAD

**Issue by fserb** [nkanaev/yarr#68]
Hi, I understand that #57 means the app is feature complete from your perspective.

That said, I added some features in [my branch](https://github.com/fserb/yarr) and I thought it would be nice to at least point them here, in case there's something that interests you. I wouldn't mind making a PR for any of them:

* Setting to enable/disable "Auto mark item as read"
* "Mark all as read" works on all views
* Show "mark all as read" and settings on all views
* Use charset from feeds instead of using the HTTP charset
* Some key-bindings change: 
  * previous/next feed with `p` and `n`
  * toggle read/unread `m`
 

If anything makes sense to you here, please let me know.

If there's no interest in any of them, it's all good. :)

Thanks for the great project.

**Comment by nkanaev** [comment]
Thanks for reaching out. I might consider making certain buttons available across all filters, but haven't decided on that yet.

Is there any reason you're relying solely on the feeds' charset?

**Comment by fserb** [comment]
Well, I have some feeds in Portuguese that use `ISO-8859-1`. For example [this one](http://feeds.folha.uol.com.br/colunas/antonioprata/rss091.xml). The situation there is:

* the HTTP request has `Content-Type: text/xml`, which is very common.
* the Feed itself has a `<?xml version="1.0" encoding="ISO-8859-1" ?>`

What was happening is that the initial HTTP conversion would convert from the default `UTF-8`, instead of leaving the data unchanged because it has no charset. By the time it got to the feed, if I tried to do the conversion, the data was already in a state where the charset conversion wouldn't work and I'd get gibberish.

The correct (spec-wise) way to do this would be: pass the charset from `Content-Type` forward as a default that can be overwritten by the feed itself and always only do one conversion. Even if there's a charset on `Content-Type`, it should be overridable by the document one and we should not do two conversions.

This was a bit too complicated given the current code, and since all of my feeds are of this type (I didn't have a single feed that passed charset on Content-Type), I just moved the conversion there.

**Comment by nkanaev** [comment]
Ah, I recall seeing those for certain feeds. Thanks for the report!

The solution: https://github.com/nkanaev/yarr/commit/982c4ebbbc284e407d7b3e0c67ebe3780db31382, albeit being hacky, should resolve the given issue.

**Comment by fserb** [comment]
This helps in my case, but it's still technically incorrect, right?

If there's a `Content-Type` with charset `UTF-8` and a feed with `encoding` for some other charset, the `UTF-8` should be ignored, not applied first.

**Comment by nkanaev** [comment]
> This helps in my case, but it's still technically incorrect, right?

Yes, that's true.

I've long given up hope on being technically correct due to numerous http/feed related issues I've encountered. Most of them have already been described in https://inessential.com/2013/03/18/brians_stupid_feed_tricks.

**Comment by tillcash** [comment]
@fserb Could you add edit feed link option? Also default the currently selected folder in New Feed pop-up window?
