### ISSUE TITLE
Compilation docker error : make: /bin/sh: Operation not permitted

### ISSUE THREAD

**Issue by citronbleuv** [nkanaev/yarr#70]
Hello,

I'm trying to run : docker build -t yarr . on my ubuntu server

But I have this error : 
![image](https://user-images.githubusercontent.com/950296/124365030-ab510580-dc45-11eb-9b9f-b8d22f9b0944.png)

I tryed to put chmod -R 777 . on the folder to test. And I have the same error.
Do you have an idea of the issue ?

Nice tool

**Comment by nkanaev** [comment]
sorry, can't help you with that.
