### ISSUE TITLE
Fail to run yarr

### ISSUE THREAD

**Issue by hmsjy2017** [nkanaev/yarr#72]
I successfully compiled yarr using docker, but failed to run the image.
```
runner@fv-az99-810:~/work/yarr$ docker run yarr
2021/07/18 04:08:43 main.go:86: using db file /data/yarr.db
2021/07/18 04:08:43 migration.go:28: db version is 0. migrating to 6
2021/07/18 04:08:43 migration.go:37: [migration:1] starting
2021/07/18 04:08:43 migration.go:63: [migration:1] failed to start transaction
2021/07/18 04:08:43 main.go:114: Failed to initialise database: unable to open database file: no such file or directory
```

**Comment by verahawk** [comment]
You have to use a Docker volume to create persistent `/data` directory. Try `docker run -v yarr-db:/data yarr`.

**Comment by tillcash** [comment]
> 
> 
> I successfully compiled yarr using docker, but failed to run the image.
> 
> ```
> runner@fv-az99-810:~/work/yarr$ docker run yarr
> 2021/07/18 04:08:43 main.go:86: using db file /data/yarr.db
> 2021/07/18 04:08:43 migration.go:28: db version is 0. migrating to 6
> 2021/07/18 04:08:43 migration.go:37: [migration:1] starting
> 2021/07/18 04:08:43 migration.go:63: [migration:1] failed to start transaction
> 2021/07/18 04:08:43 main.go:114: Failed to initialise database: unable to open database file: no such file or directory
> ```

Could you share the image?
