### ISSUE TITLE
Nitter - No feeds found at given url

### ISSUE THREAD

**Issue by genxlee** [nkanaev/yarr#74]
yarr is unable to load RSS feed from Nitter (https://github.com/zedeus/nitter/) instances.

Example links:
- https://nitter.net/rss/rss
- https://nitter.net/rss,github/rss

**Comment by nkanaev** [comment]
niiter.net has a certificate signed by letsencrypt, and your system doesn't seem to have it's intermediate certificate (https://letsencrypt.org/certificates/#intermediate-certificates)

adding it solved the issue for me. hope that helps.
