### ISSUE TITLE
Working binary for Mojave?

### ISSUE THREAD

**Issue by acagastya** [nkanaev/yarr#76]
Hi, I was trying yarr on macos 10.14; and seems like the pre-compiled binary is not suitable for this OS.  While I can compile it and have been using it like that -- could you perhaps have an official build of it made available in releases and brew.sh?  I'd be happt to compile and share the binary, if you don't have the old OS.

**Comment by nkanaev** [comment]
hi, the binaries are built by github actions, and the 10.15 is the earliest version provided. supporting various platforms & distributions takes time and effort. unfortunately i cannot dedicate my time on that.

feel free to distribute your own copies.
