### ISSUE TITLE
Browser back-button support

### ISSUE THREAD

**Issue by icyphox** [nkanaev/yarr#78]
Hi, I've been using yarr for the past year or so, mostly on my phone, and while I'm loving it, the lack of support for navigating pages via the back/forward buttons in the browser still trips me up.

I realize that yarr is feature complete but I know basically nothing of Vue and have no idea where to begin. It would be great if you could implement this feature, or give me some pointers on how I could do this myself.

Thanks!

**Comment by nkanaev** [comment]
hi,

do you mean mobile browsers' back/forward buttons? i think there is no quick solution for that, it'd involve radical changes in the frontend's navigation system.

perhaps pwa could be a solution (with the navigation bar hidden), but nobody has stepped forward to implement that (https://github.com/nkanaev/yarr/issues/48).

**Comment by icyphox** [comment]
I see, that makes sense. I guess I'll just get used to it then, heh.
Thanks, again.

--
Anirudh Oppiliappan
https://icyphox.sh

**Comment by thanhnguyen2187** [comment]
Hi @nkanaev. I'm thinking of tackling this myself since it is one functionality I miss migrating from Inoreader. My approach for this is to handle event `popstate`, and change the UI state correspondingly (from opening a feed item to not opening, etc.). Do you think that this is feasible?

**Comment by nkanaev** [comment]
@thanhnguyen2187 I don't think messing with browser's history state is a good idea. If it were possible to handle back button for mobile-only usage (without hacks), that could be an optimal solution.
