### ISSUE TITLE
[Feat req] Mark all entries of a feed as read

### ISSUE THREAD

**Issue by acagastya** [nkanaev/yarr#79]
Hi, I have been using yarr a few months now, and I feel, having an option to mark all entries from a given feed as read would be a good addition.  I know #57 says yarr is feature complete, but if it is not too much to ask, can that feature please be implemented?

---
Maybe an entry "Mark all as read"?
<img width="297" alt="Screenshot 2021-11-06 at 06 04 55" src="https://user-images.githubusercontent.com/5466083/140601852-646021bc-3962-4d9d-8a28-c7a264669b91.png">

**Comment by nkanaev** [comment]
marking items as read (along with the unread count stats) is available only if "unread" filter is selected.

that's by design. sorry.
