### ISSUE TITLE
RSS feed parsing issue?

### ISSUE THREAD

**Issue by stepelu** [nkanaev/yarr#88]
The RSS feed https://francisbach.com/feed/ results in the parse error `XML syntax error on line 1815: illegal character code U+000C`.
I might be mistaken but I cannot find this unicode character in the feed itself, so I am unsure about what might be happening here.
Tested on Linux, git HEAD as time of this Issue creation.

**Comment by nkanaev** [comment]
`\x0c` is there, on line 1786 (attached feed content: [francisbach.xml.txt](https://github.com/nkanaev/yarr/files/7941606/francisbach.xml.txt))

Go's xml decoder is strict in that regard. *yarr* should be able to handle such nuisances.

**Comment by nkanaev** [comment]
the fix has landed on master branch. needs thorough testing and will be available in the upcoming release.
