### ISSUE TITLE
The text in the "Keyboard Shortcuts" list isn't readable in the dark theme

### ISSUE THREAD

**Issue by John09f9** [nkanaev/yarr#92]
I.e. dark text on a black background. Screenshot: https://user-images.githubusercontent.com/14362564/156091537-58d46d0a-dcc9-4541-890e-aaf705a1c75a.png

The text in other sections is fine. Screenshot: https://user-images.githubusercontent.com/14362564/156091774-7737f83a-d581-4419-8450-f421c7c7a4cf.png

Versions:

- yarr v2.2 on Windows
- Screenshots taken in Chrome v98, Stable Channel. 

Cheers!

**Comment by nkanaev** [comment]
fixed. thanks
