### ISSUE TITLE
Articles not loading due to lack of scrolling

### ISSUE THREAD

**Issue by bielej** [nkanaev/yarr#93]
Basically, when the page is zoomed out or displayed on a high DPI display, articles won't load.  
![image](https://user-images.githubusercontent.com/11682584/161931832-07be66a6-6c48-4ef7-a0f2-d5fc841b41d3.png)
If you zoom in the page the articles will load just fine, but zooming in every time to load new articles is a little bit annoying.

**Comment by bielej** [comment]
A temporary fix can be made by adjusting the amount of entries per page
```
server/routes.go
312:            perPage := 20
```

**Comment by nkanaev** [comment]
@bielej thanks for the report. fixed in https://github.com/nkanaev/yarr/commit/684bc25b833a71377f1b54383784d4d259b75ad0.
