### ISSUE TITLE
Jump to internal links

### ISSUE THREAD

**Issue by ghost** [nkanaev/yarr#94]
For example, clicking on reference no. 1 takes me to author's website.

![Screenshot from 2022-04-27 16-07-39](https://user-images.githubusercontent.com/87414805/165495317-ec5a558b-e997-4463-bdbd-6daac4b8e862.png)

**Comment by nkanaev** [comment]
The website is available in feeds' menu:

![Screenshot from 2022-05-03 15-38-53](https://user-images.githubusercontent.com/4911300/166475471-1a087a35-0f0d-4bfa-8936-461bbb345b53.png)

Otherwise it can be reached by clicking the feed external link & navigating within the website.

**Comment by arikq** [comment]
@nkanaev I can't understand your reply.

I was asking, if I click on a internal like a reference/footnote, I wanted the post to jump to that relevant part, to where it is pointing to. But currently it takes me to the website, treating internal links as others.

**Comment by nkanaev** [comment]
all the links in the post are expanded against the post's url and made external, including internal ones.
leaving internal/reference links as is may lead to issues with the *yarr's* interface, since it's html too.

**Comment by esdnm** [comment]
> leaving internal/reference links as is may lead to issues with the yarr's interface, since it's html too.

Can it be handled using JS?
