### ISSUE TITLE
Auto Refresh时间能否由用户自行控制，或者增加更短的刷新间隔

### ISSUE THREAD

**Issue by zangbob** [nkanaev/yarr#95]
非常感谢您的作品YARR，很好用+很实用。唯一遗憾，就是刷新间隔时间较长。在跟踪一些时效性信息时，10分钟的间隔太长，只能手动刷新。

不知可否增加一个用户自定义刷新间隔的功能？  如果自定义时间太复杂的话，那能否增加一个5分钟、或3分钟这样较短的刷新间隔？

8手"码农"，业余选手中的业余选手，对GO一窍不同，甚至都不会搭建环境那种，更不用说自己编译了。。

**Comment by nkanaev** [comment]
Hi, thanks.

I'd prefer intervals to stay the way they are right now.

But changing the refresh interval is possible by updating the database (no compiling required):

```shell
$ sqlite3 /path/to/your/storage.db 'insert into settings (key, val) values ("refresh_rate", X) on conflict (key) do update set val=X'
```
Change `X` with the one desired (it's in minutes btw).
