### ISSUE TITLE
Is it feasible to publicly self-host yarr with a pre-defined set of RSS feeds?

### ISSUE THREAD

**Issue by preslavrachev** [nkanaev/yarr#97]
I am looking for a way to showcase a few custom RSS feeds. I'd ideally self-host yarr and add the feeds myself. However, I would like to disable the ability for outsiders to add their own feeds or change mine. 

How feasible is it to provide a read-only view of yarr?

**Comment by nkanaev** [comment]
the easiest way is to start an instance with custom `-db` parameter:

```
$ yarr -db "file:/path/to/storage.db?mode=ro"
```

this will, of course, generate lots of `attempt to write a readonly database` errors in the output log.
